name: coveralls

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:
      project: dotnet-rpg.sln
      verbosity: detailed
    
    environment:
      COVERALLS_REPO_TOKEN:
        secure: secrets.COVERALLS_TOKEN
 