name: Test Coveralls

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.2.0
