name: Test Coveralls

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  - name: Run automated unit and integration tests
    run: dotnet test tests/dotnet-rpg.Web.UnitTests/dotnet-rpg.Web.UnitTests.csproj
    
  - name: Coveralls
    run: coverallsapp/github-action@v2
